/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pruebafiguras;

/**
 *
 * @author jefeg
 */
public class VentanaPruebaFiguras extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPruebaFiguras
     */
    public VentanaPruebaFiguras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        adas = new javax.swing.JLabel();
        dasasf = new javax.swing.JLabel();
        txtCiRadio = new javax.swing.JTextField();
        txtCiArea = new javax.swing.JTextField();
        txtCiPerimetro = new javax.swing.JTextField();
        btnCiArea = new javax.swing.JButton();
        btnCiPerimetro = new javax.swing.JButton();
        btnCiBorrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCuLado = new javax.swing.JTextField();
        txtCuArea = new javax.swing.JTextField();
        txtCuPerimetro = new javax.swing.JTextField();
        btnCuArea = new javax.swing.JButton();
        btnCuPerimetro = new javax.swing.JButton();
        btnCuBorrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtReBase = new javax.swing.JTextField();
        txtReAltura = new javax.swing.JTextField();
        txtReArea = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtRePerimetro = new javax.swing.JTextField();
        btnReArea = new javax.swing.JButton();
        btnRePerimetro = new javax.swing.JButton();
        btnReBorrar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnTHipotenusa = new javax.swing.JButton();
        btnTArea = new javax.swing.JButton();
        btnTPerimetro = new javax.swing.JButton();
        btnTTipo = new javax.swing.JButton();
        btnTBorrar = new javax.swing.JButton();
        txtTBase = new javax.swing.JTextField();
        txtTAltura = new javax.swing.JTextField();
        txtTHipotenusa = new javax.swing.JTextField();
        txtTArea = new javax.swing.JTextField();
        txtTPerimetro = new javax.swing.JTextField();
        txtTTipo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Circulo");

        a.setText("Radio");

        adas.setText("Area");

        dasasf.setText("Perimetro");

        txtCiPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCiPerimetroActionPerformed(evt);
            }
        });

        btnCiArea.setText("Area");
        btnCiArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCiAreaActionPerformed(evt);
            }
        });

        btnCiPerimetro.setText("Perimetro");
        btnCiPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCiPerimetroActionPerformed(evt);
            }
        });

        btnCiBorrar.setText("Borrar");
        btnCiBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCiBorrarActionPerformed(evt);
            }
        });

        jLabel2.setText("Lado");

        jLabel3.setText("Area");

        jLabel4.setText("Perimetro");

        jLabel5.setText("Cuadrado");

        btnCuArea.setText("Area");
        btnCuArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuAreaActionPerformed(evt);
            }
        });

        btnCuPerimetro.setText("Perimetro");
        btnCuPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuPerimetroActionPerformed(evt);
            }
        });

        btnCuBorrar.setText("Borrar");
        btnCuBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuBorrarActionPerformed(evt);
            }
        });

        jLabel6.setText("Rectangulo");

        jLabel7.setText("Base");

        jLabel8.setText("Altura");

        jLabel9.setText("Area");

        txtReBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReBaseActionPerformed(evt);
            }
        });

        jLabel10.setText("Perimetro");

        btnReArea.setText("Area");
        btnReArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReAreaActionPerformed(evt);
            }
        });

        btnRePerimetro.setText("Perimetro");
        btnRePerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRePerimetroActionPerformed(evt);
            }
        });

        btnReBorrar.setText("Borrar");
        btnReBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReBorrarActionPerformed(evt);
            }
        });

        jLabel11.setText("Triangulo Rectangulo");

        jLabel12.setText("Altura");

        jLabel13.setText("Base");

        jLabel14.setText("Hipotenusa");

        jLabel15.setText("Area");

        jLabel16.setText("Perimetro");

        jLabel17.setText("Tipo de triangulo");

        btnTHipotenusa.setText("Hipotenusa");
        btnTHipotenusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTHipotenusaActionPerformed(evt);
            }
        });

        btnTArea.setText("Area");
        btnTArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTAreaActionPerformed(evt);
            }
        });

        btnTPerimetro.setText("Perimetro");
        btnTPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTPerimetroActionPerformed(evt);
            }
        });

        btnTTipo.setText("Tipo de triangulo");
        btnTTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTTipoActionPerformed(evt);
            }
        });

        btnTBorrar.setText("Borrar");
        btnTBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTBorrarActionPerformed(evt);
            }
        });

        txtTTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRePerimetro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReBorrar))
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adas)
                                    .addComponent(a)
                                    .addComponent(dasasf))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCiPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCiArea, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtCiRadio)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCiArea, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCiPerimetro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCiBorrar))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtRePerimetro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                        .addComponent(txtReArea, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtReAltura, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtReBase, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCuLado, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCuArea, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCuPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTHipotenusa)
                                            .addComponent(txtTPerimetro)
                                            .addComponent(txtTTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                            .addComponent(txtTArea)
                                            .addComponent(txtTAltura)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCuArea)
                                            .addComponent(jLabel13))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnCuPerimetro)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnCuBorrar))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(txtTBase, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(jLabel11)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 253, Short.MAX_VALUE)
                .addComponent(btnTHipotenusa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTPerimetro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTBorrar)
                .addGap(354, 354, 354))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a)
                    .addComponent(txtCiRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtCuLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adas)
                    .addComponent(txtCiArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtCuArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dasasf)
                    .addComponent(txtCiPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtCuPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCiArea)
                    .addComponent(btnCiPerimetro)
                    .addComponent(btnCiBorrar)
                    .addComponent(btnCuArea)
                    .addComponent(btnCuPerimetro)
                    .addComponent(btnCuBorrar))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtReBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtReAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtTAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txtTBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtReArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txtTHipotenusa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtRePerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtTArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnReArea)
                        .addComponent(btnRePerimetro)
                        .addComponent(btnReBorrar))
                    .addComponent(txtTPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtTTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTHipotenusa)
                    .addComponent(btnTArea)
                    .addComponent(btnTPerimetro)
                    .addComponent(btnTTipo)
                    .addComponent(btnTBorrar))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCiPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCiPerimetroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiPerimetroActionPerformed

    private void btnCiAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCiAreaActionPerformed
        float radio = Float.parseFloat(txtCiRadio.getText());
        Circulo circulo1 = new Circulo(radio);
        txtCiArea.setText(String.valueOf(circulo1.area()));
    }//GEN-LAST:event_btnCiAreaActionPerformed

    private void btnCiPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCiPerimetroActionPerformed
        float radio = Float.parseFloat(txtCiRadio.getText());
        Circulo circulo1 = new Circulo(radio);
        txtCiPerimetro.setText(String.valueOf(circulo1.perimetro()));
    }//GEN-LAST:event_btnCiPerimetroActionPerformed

    private void btnCiBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCiBorrarActionPerformed
        txtCiRadio.setText("");
        txtCiArea.setText("");
        txtCiPerimetro.setText("");
    }//GEN-LAST:event_btnCiBorrarActionPerformed

    private void btnCuAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuAreaActionPerformed
       float lado = Float.parseFloat(txtCuLado.getText());
       Cuadrado cuadrado1 = new Cuadrado(lado);
       txtCuArea.setText(String.valueOf(cuadrado1.area()));
    }//GEN-LAST:event_btnCuAreaActionPerformed

    private void btnCuPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuPerimetroActionPerformed
        float lado = Float.parseFloat(txtCuLado.getText());
       Cuadrado cuadrado1 = new Cuadrado(lado);
       txtCuPerimetro.setText(String.valueOf(cuadrado1.perimetro()));
    }//GEN-LAST:event_btnCuPerimetroActionPerformed

    private void btnCuBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuBorrarActionPerformed
        txtCuLado.setText("");
        txtCuArea.setText("");
        txtCuPerimetro.setText("");
    }//GEN-LAST:event_btnCuBorrarActionPerformed

    private void txtReBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReBaseActionPerformed

    private void btnReAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReAreaActionPerformed
        float base = Float.parseFloat(txtReBase.getText());
        float altura = Float.parseFloat(txtReAltura.getText());
        Rectangulo rectangulo1 = new Rectangulo(base,altura);
        txtReArea.setText(String.valueOf(rectangulo1.area()));
    }//GEN-LAST:event_btnReAreaActionPerformed

    private void btnRePerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRePerimetroActionPerformed
        float base = Float.parseFloat(txtReBase.getText());
        float altura = Float.parseFloat(txtReAltura.getText());
        Rectangulo rectangulo1 = new Rectangulo(base,altura);
        txtRePerimetro.setText(String.valueOf(rectangulo1.perimetro()));
    }//GEN-LAST:event_btnRePerimetroActionPerformed

    private void btnReBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReBorrarActionPerformed
        txtReBase.setText("");
        txtReAltura.setText("");
        txtReArea.setText("");
        txtRePerimetro.setText("");
    }//GEN-LAST:event_btnReBorrarActionPerformed

    private void txtTTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTTipoActionPerformed

    private void btnTHipotenusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTHipotenusaActionPerformed
        float base = Float.parseFloat(txtTBase.getText());
        float altura = Float.parseFloat(txtTAltura.getText());
        TrianguloRectangulo triangulo1 = new TrianguloRectangulo(base,altura);
        txtTHipotenusa.setText(String.valueOf(triangulo1.hipotenusa()));
    }//GEN-LAST:event_btnTHipotenusaActionPerformed

    private void btnTAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTAreaActionPerformed
         float base = Float.parseFloat(txtTBase.getText());
        float altura = Float.parseFloat(txtTAltura.getText());
        TrianguloRectangulo triangulo1 = new TrianguloRectangulo(base,altura);
        txtTArea.setText(String.valueOf(triangulo1.area()));
    }//GEN-LAST:event_btnTAreaActionPerformed

    private void btnTPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTPerimetroActionPerformed
         float base = Float.parseFloat(txtTBase.getText());
        float altura = Float.parseFloat(txtTAltura.getText());
        TrianguloRectangulo triangulo1 = new TrianguloRectangulo(base,altura);
        txtTPerimetro.setText(String.valueOf(triangulo1.perimetro()));
    }//GEN-LAST:event_btnTPerimetroActionPerformed

    private void btnTTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTTipoActionPerformed
         float base = Float.parseFloat(txtTBase.getText());
        float altura = Float.parseFloat(txtTAltura.getText());
        TrianguloRectangulo triangulo1 = new TrianguloRectangulo(base,altura);
        txtTTipo.setText(triangulo1.tipoDeTriangulo());
    }//GEN-LAST:event_btnTTipoActionPerformed

    private void btnTBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTBorrarActionPerformed
        txtTBase.setText("");
        txtTAltura.setText("");
        txtTHipotenusa.setText("");
        txtTArea.setText("");
        txtTPerimetro.setText("");
        txtTTipo.setText("");
    }//GEN-LAST:event_btnTBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPruebaFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPruebaFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPruebaFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPruebaFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPruebaFiguras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JLabel adas;
    private javax.swing.JButton btnCiArea;
    private javax.swing.JButton btnCiBorrar;
    private javax.swing.JButton btnCiPerimetro;
    private javax.swing.JButton btnCuArea;
    private javax.swing.JButton btnCuBorrar;
    private javax.swing.JButton btnCuPerimetro;
    private javax.swing.JButton btnReArea;
    private javax.swing.JButton btnReBorrar;
    private javax.swing.JButton btnRePerimetro;
    private javax.swing.JButton btnTArea;
    private javax.swing.JButton btnTBorrar;
    private javax.swing.JButton btnTHipotenusa;
    private javax.swing.JButton btnTPerimetro;
    private javax.swing.JButton btnTTipo;
    private javax.swing.JLabel dasasf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCiArea;
    private javax.swing.JTextField txtCiPerimetro;
    private javax.swing.JTextField txtCiRadio;
    private javax.swing.JTextField txtCuArea;
    private javax.swing.JTextField txtCuLado;
    private javax.swing.JTextField txtCuPerimetro;
    private javax.swing.JTextField txtReAltura;
    private javax.swing.JTextField txtReArea;
    private javax.swing.JTextField txtReBase;
    private javax.swing.JTextField txtRePerimetro;
    private javax.swing.JTextField txtTAltura;
    private javax.swing.JTextField txtTArea;
    private javax.swing.JTextField txtTBase;
    private javax.swing.JTextField txtTHipotenusa;
    private javax.swing.JTextField txtTPerimetro;
    private javax.swing.JTextField txtTTipo;
    // End of variables declaration//GEN-END:variables
}
